# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-15 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default='1', max_length=30),
            preserve_default=False,
        ),
    ]
