# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-25 07:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20170822_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_at', models.DateTimeField(blank=True, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberInTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubscriberInTeam', to='accounts.Subscriber')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubscriberInTeam', to='accounts.Team')),
            ],
            options={
                'ordering': ['-team', '-subscriber'],
            },
        ),
        migrations.CreateModel(
            name='TeamTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChildTeam', to='accounts.Team')),
                ('perent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PerentTeam', to='accounts.Team')),
            ],
            options={
                'ordering': ['-perent'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Team', to='accounts.Subscriber'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='teamtree',
            unique_together=set([('perent', 'child')]),
        ),
        migrations.AlterUniqueTogether(
            name='subscriberinteam',
            unique_together=set([('team', 'subscriber')]),
        ),
    ]
