# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-25 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170825_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberinteam',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teamtree',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
