# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-25 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170825_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamtree',
            options={'ordering': ['-parent']},
        ),
        migrations.RenameField(
            model_name='teamtree',
            old_name='perent',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='company',
            name='ceo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Company', to='accounts.Subscriber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='lead_group',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Company', to='accounts.Team'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='teamtree',
            unique_together=set([('parent', 'child')]),
        ),
    ]
