# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-26 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170826_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='ceo',
        ),
        migrations.RemoveField(
            model_name='company',
            name='lead_group',
        ),
    ]
