# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-26 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170826_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CompanySubscriber', to='accounts.Company')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CompanySubscriber', to='accounts.Subscriber')),
            ],
            options={
                'ordering': ['-company'],
            },
        ),
        migrations.CreateModel(
            name='CompanyTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CompanyTeam', to='accounts.Company')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CompanyTeam', to='accounts.Team')),
            ],
            options={
                'ordering': ['-company'],
            },
        ),
        migrations.CreateModel(
            name='TeamSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamSubscriber', to='accounts.Subscriber')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamSubscriber', to='accounts.Team')),
            ],
            options={
                'ordering': ['-team', '-subscriber'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='subscriberinteam',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='subscriberinteam',
            name='subscriber',
        ),
        migrations.RemoveField(
            model_name='subscriberinteam',
            name='team',
        ),
        migrations.DeleteModel(
            name='SubscriberInTeam',
        ),
        migrations.AlterUniqueTogether(
            name='teamsubscriber',
            unique_together=set([('team', 'subscriber')]),
        ),
        migrations.AlterUniqueTogether(
            name='companyteam',
            unique_together=set([('company', 'team')]),
        ),
        migrations.AlterUniqueTogether(
            name='companysubscriber',
            unique_together=set([('company', 'subscriber')]),
        ),
    ]
