# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-26 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170826_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsubscriber',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
