# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-26 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_teamsubscriber_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='leader',
        ),
        migrations.AddField(
            model_name='teamsubscriber',
            name='manager',
            field=models.BooleanField(default=False),
        ),
    ]
